repos:
- repo: https://github.com/pycqa/isort
  rev: 5.11.2
  hooks:
    - id: isort
      name: isort (python)

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: "v0.32.0" # Use the sha / tag you want to point at
  hooks:
    - id: yapf
      additional_dependencies: ["toml"]
