name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "system-features = benchmark big-parallel kvm nixos-test uid-range"
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build -L .#tests.x86_64-linux.module
